### PR TITLE
QickSweep can now calclate the actual rounded sweep points

### PR DESCRIPTION
**Pull request by yoshi74ls181**
Added `QickSweep.get_actual_values`, which calculates the actual sweep points after rounding to ASM units. There are also some unrelated fixes:

- Documented the keyword argument `ro_ch` for `QickProgramV2.add_pulse`
- Fixed a typo in `pyro.make_proxy`

### CODE REVIEW

**Comment by meeg** [comment]
Looks good, thanks!

I am a little worried that `QickSweep.get_actual_values()` is largely redundant with `QickProgramV2.get_pulse_param()` but they both work, I don't want to get in your way, and your solution might be better. I can think about it later, and for now I am happy to merge this.

**Comment by yoshi74ls181** [comment]
Thank you very much for the quick merge!

> I am a little worried that `QickSweep.get_actual_values()` is largely redundant with `QickProgramV2.get_pulse_param()`

The advantage of the new `QickSweep.get_actual_values()` is that it works for a `Delay` as well as for a `Pulse`. A disadvantage might be that its implementation involves recursions and closures. If that is not a big concern, maybe it's a good idea to rewrite `QickProgramV2.get_pulse_param()` to use the new `QickSweep.get_actual_values()`. The former will still be useful because the user doesn't need to pass to it the loop order and numbers of iterations.

**Comment by meeg** [comment]
Yes, agree that it's important to be able to get rounded delays. My idea for that was that you can specify an arbitrary "tag" string as a parameter to a timed instruction (pulse, trigger, delay, wait), and then you can do something like `QickProgramV2.get_time_param(tag)`. Does that sound good?

If `get_pulse_param()` and `get_time_param()` are sufficient I would want to make those the preferred user interface, because they work with scalar values as well as sweeps. And I agree, probably both should use `get_actual_values()` internally, I think it is a better design than what I had.

**Comment by yoshi74ls181** [comment]
Your idea for `get_time_param(tag)` sounds good! `get_pulse_param()` and `get_time_param()` can be the preferred user interface when using `qick_lib` directly, but for writing our QCoDeS driver `QickSweep.get_actual_values()` makes more sense because it works in the same way for pulses and delays.

**Pull request merged**
